#!/bin/bash

# Questa Web Interface - Deployment Configuration Script
# This script helps configure the application for deployment to a new server

set -e

# Check if we're in the right directory
if [ ! -f ecosystem.config.js ]; then
  echo "ERROR: Please run this script from the project root directory." >&2
  exit 1
fi

# Check if .env already exists
if [ -f .env ]; then
  echo "WARNING: .env file already exists."
  read -p "Do you want to overwrite it? (y/N): " OVERWRITE
  case "$OVERWRITE" in
    y|Y) ;;
    *) echo "Configuration cancelled."; exit 0;;
  esac
fi

echo "=== Questa Web Interface - Deployment Configuration ==="
echo

# Prompt for QuestaSim paths
echo "Step 1: QuestaSim Installation Paths"
read -p "Enter path to QuestaSim modeltech directory (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/modeltech/linux_x86_64): " QUESTA_MODELTECH_PATH
read -p "Enter path to vlog executable (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/modeltech/linux_x86_64/vlog): " QUESTA_VLOG_PATH
read -p "Enter path to vopt executable (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/modeltech/linux_x86_64/vopt): " QUESTA_VOPT_PATH
read -p "Enter path to vsim executable (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/modeltech/linux_x86_64/vsim): " QUESTA_VSIM_PATH
read -p "Enter path to Questa Formal bin directory (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/bin): " QUESTA_FORMAL_PATH
read -p "Enter path to qverify executable (e.g. /opt/QOSF_2024.3/questa_static_formal/linux_x86_64/bin/qverify): " QUESTA_QVERIFY_PATH

echo
# Prompt for network config
echo "Step 2: Network Configuration"
DEFAULT_IP=$(hostname -I | awk '{print $1}')
read -p "Enter server IP address [${DEFAULT_IP}]: " HOST_IP
HOST_IP=${HOST_IP:-$DEFAULT_IP}
read -p "Enter backend port [3001]: " BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-3001}
read -p "Enter frontend port [3000]: " FRONTEND_PORT
FRONTEND_PORT=${FRONTEND_PORT:-3000}

echo
# Prompt for license server
echo "Step 3: License Configuration"
read -p "Enter license server (e.g. 29000@yourlicenseserver): " LICENSE_SERVER
LICENSE_SERVER=${LICENSE_SERVER:-29000@vbox}

# Write .env file
cat > .env <<EOF
# Questa Web Interface Environment Configuration
# Generated by deploy-config.sh on $(date)

# Network Configuration
HOST_IP=$HOST_IP
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT

# Environment
NODE_ENV=development

# Logging
LOG_LEVEL=info

# QuestaSim Tool Paths Configuration
QUESTA_MODELTECH_PATH=$QUESTA_MODELTECH_PATH
QUESTA_VLOG_PATH=$QUESTA_VLOG_PATH
QUESTA_VOPT_PATH=$QUESTA_VOPT_PATH
QUESTA_VSIM_PATH=$QUESTA_VSIM_PATH
QUESTA_FORMAL_PATH=$QUESTA_FORMAL_PATH
QUESTA_QVERIFY_PATH=$QUESTA_QVERIFY_PATH

# License Configuration
LICENSE_SERVER=$LICENSE_SERVER
SALT_LICENSE_SERVER=$LICENSE_SERVER

# Optional: Override automatic IP detection
# AUTO_DETECT_IP=false

# Optional: Specific network interface (if multiple)
# NETWORK_INTERFACE=eth0

# PM2 specific settings
# PM2_INSTANCES=1
# PM2_MAX_MEMORY=1G
EOF

echo
cat .env

echo "\nSUCCESS: .env file created successfully!"
echo "You can now run 'npm install' in backend/frontend and start with pm2." 